version: '3'

networks:
  symreact_subnet:
    external: true

services:
  database:
    image: mysql:5.7
    networks:
      symreact_subnet:
        ipv4_address: 172.24.0.6
    container_name: database-symreact
    working_dir: /var/www/symreact

    environment:
      - MYSQL_USER=symreact
      - MYSQL_PASSWORD=symreact
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symreact_db
    ports:
      - "3306:3306"

    volumes:
      - .:/var/www/symreact

  nginx:
    image: nginx:alpine
    networks:
      symreact_subnet:
        ipv4_address: 172.24.0.5
    container_name: nginx-symreact
    working_dir: /var/www/symreact
    volumes:
      - .:/var/www/symreact
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"

  php:
    build: docker/php
    networks:
      symreact_subnet:
        ipv4_address: 172.24.0.4
    container_name: php-symreact
    working_dir: /var/www/symreact
    ports:
      - "9000:9000"
    extra_hosts:
      - "plateforme-echange-securise.localhost: 172.22.0.1"

    depends_on:
      - database
    volumes:
      - .:/var/www/symreact
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini

  node:
    image: node:14.17-slim
    container_name: node-symreact
    networks:
      symreact_subnet:
        ipv4_address: 172.24.0.3
    ports:
      - "3000:3000"
    volumes:
      - .:/var/www/symreact
    working_dir: /var/www/symreact
    tty: true
    stdin_open: true

  adminer:
    image: adminer
    container_name: adminer-symreact
    networks:
      symreact_subnet:
        ipv4_address: 172.24.0.7
    restart: always
    ports:
      - "8081:8080"